import { randomBytes,randomUUID } from "node:crypto";
import Fastify from "fastify";import rateLimit from "@fastify/rate-limit";import { Type } from "@sinclair/typebox";
import { AnalysisStatusV1Schema,CreateAnalysisRequestV1Schema,CreateAnalysisResponseV1Schema,LbtiReportV1Schema,assertSchema } from "@lol-sbti/contracts";import type { AnalysisRepository } from "@lol-sbti/persistence";
const Strict=<T extends Record<string,any>>(p:T)=>Type.Object(p,{additionalProperties:false}),Id=Type.String({pattern:"^(?:ana|pub)_[A-Za-z0-9_]+$",maxLength:128}),AuthHeaders=Type.Object({authorization:Type.String({minLength:39,maxLength:520})},{additionalProperties:true}),Error=Strict({code:Type.String()});
const token=()=>randomBytes(32).toString("base64url"),bearer=(h:string|undefined)=>h?.match(/^Bearer ([A-Za-z0-9_-]{32,512})$/)?.[1],cookie=(h:string|undefined,name:string)=>h?.split(";").map(x=>x.trim().split("=")).find(x=>x[0]===name)?.[1];
export function buildApp(repository:AnalysisRepository,options:{baseUrl?:string;logger?:any}={}){const logger=options.logger===false?false:{...options.logger,redact:{paths:["req.headers.authorization","req.headers.cookie","req.body","res.headers.set-cookie","err.headers","err.body","err.secret","err.response","err.cause"],censor:"[REDACTED]"}};const app=Fastify({logger,bodyLimit:1024*1024,ajv:{customOptions:{removeAdditional:false},plugins:[ajv=>{ajv.addFormat("lol-sbti-utc-timestamp",{type:"string",validate:(v:string)=>{const m=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})(?::(\d{2})(?:\.(\d{1,3}))?)?Z$/.exec(v);if(!m)return false;const p=[m[1],m[2],m[3],m[4],m[5],m[6]??"0"].map(Number),d=new Date(Date.UTC(p[0]!,p[1]!-1,p[2],p[3],p[4],p[5],Number((m[7]??"0").padEnd(3,"0"))));return d.getUTCFullYear()===p[0]&&d.getUTCMonth()===p[1]!-1&&d.getUTCDate()===p[2]&&d.getUTCHours()===p[3]&&d.getUTCMinutes()===p[4]&&d.getUTCSeconds()===p[5]}});return ajv} ]}});
 app.register(rateLimit,{global:true,max:100,timeWindow:"1 minute",keyGenerator:req=>`${req.ip}:${String(req.headers.authorization??"").slice(-16)}`});
 app.post("/v1/installations",{config:{rateLimit:{max:10,timeWindow:"1 hour"}},schema:{body:Strict({clientVersion:Type.String({minLength:1,maxLength:64,pattern:"^[A-Za-z0-9._+-]+$"})}),response:{201:Strict({installationCredential:Type.String({minLength:32,maxLength:512})}),400:Error}}},async(_q,r)=>{const c=token();await repository.createInstallation(`ins_${randomUUID().replaceAll("-","")}`,c);return r.code(201).send({installationCredential:c})});
 app.post("/v1/analyses",{config:{rateLimit:{max:20,timeWindow:"1 day"}},schema:{body:CreateAnalysisRequestV1Schema,headers:Type.Object({authorization:Type.String({minLength:39,maxLength:520}),"idempotency-key":Type.String({format:"uuid"})},{additionalProperties:true}),response:{202:CreateAnalysisResponseV1Schema,400:Error,401:Error}}},async(q,r)=>{const h=q.headers as Record<string,string|undefined>,credential=bearer(h.authorization);if(!credential)return r.code(401).send({code:"UNAUTHORIZED"});const installationId=await repository.authenticateInstallation(credential);if(!installationId)return r.code(401).send({code:"UNAUTHORIZED"});const now=Date.now(),created=await repository.createAnalysis({id:`ana_${randomUUID().replaceAll("-","")}`,installationId,idempotencyKey:h["idempotency-key"]!,payload:q.body,inputExpiresAt:new Date(now+3600_000),resultExpiresAt:new Date(now+86400_000),jobId:`job_${randomUUID().replaceAll("-","")}`});return r.code(202).send({analysisId:created.analysis.id,status:"queued",receiptToken:created.receiptToken,pollAfterMs:2000,inputExpiresAt:created.analysis.inputExpiresAt.toISOString()})});
 app.get("/v1/analyses/:analysisId",{schema:{params:Strict({analysisId:Id}),headers:AuthHeaders,response:{200:AnalysisStatusV1Schema,404:Error}}},async(q,r)=>{const id=(q.params as any).analysisId,receipt=bearer((q.headers as any).authorization),a=receipt&&await repository.findByReceipt(id,receipt);if(!a)return r.code(404).send({code:"NOT_FOUND"});if(a.status==="completed"&&a.publicId&&a.shareExpiresAt&&a.shareSecret)return{analysisId:id,status:"completed",share:{url:`${options.baseUrl??process.env.PUBLIC_REPORT_BASE_URL??"https://app.example/r"}/${a.publicId}#${a.shareSecret}`,expiresAt:a.shareExpiresAt.toISOString()}};if(a.status==="failed")return{analysisId:id,status:"failed",error:{code:a.errorCode??"ANALYSIS_FAILED",retryable:Boolean(a.retryable)}};if(a.status==="expired"||a.status==="deleted")return{analysisId:id,status:a.status};return{analysisId:id,status:a.status,stage:a.status==="processing"?"llm_analysis":a.status,pollAfterMs:3000}});
 app.post("/v1/analyses/:analysisId/retry",{schema:{params:Strict({analysisId:Id}),headers:AuthHeaders,response:{202:Strict({analysisId:Id,status:Type.Literal("queued")}),409:Error,404:Error}}},async(q,r)=>{const receipt=bearer((q.headers as any).authorization);if(!receipt)return r.code(404).send({code:"NOT_FOUND"});return await repository.retryAnalysis((q.params as any).analysisId,receipt,3)?r.code(202).send({analysisId:(q.params as any).analysisId,status:"queued"}):r.code(409).send({code:"RETRY_NOT_ALLOWED"})});
 app.post("/v1/share-sessions",{config:{rateLimit:{max:20,timeWindow:"1 minute"}},schema:{body:Strict({publicId:Id,secret:Type.String({minLength:32,maxLength:512})}),response:{204:Type.Null(),404:Error,410:Error}}},async(q,r)=>{const {publicId,secret}=q.body as any,s=token(),state=await repository.createShareSession(publicId,secret,s,new Date(Date.now()+15*60_000));if(state==="not_found")return r.code(404).send({code:"NOT_FOUND"});if(state==="gone")return r.code(410).send({code:"GONE"});r.header("set-cookie",`report_session=${s}; Path=/v1/public/reports/${publicId}; Max-Age=900; HttpOnly; Secure; SameSite=Lax`);return r.code(204).send()});
 app.get("/v1/public/reports/:publicId",{schema:{params:Strict({publicId:Id}),response:{200:LbtiReportV1Schema,404:Error,410:Error}}},async(q,r)=>{r.headers({"cache-control":"private, no-store","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-robots-tag":"noindex, nofollow, noarchive"});const id=(q.params as any).publicId,s=cookie(q.headers.cookie,"report_session");if(!s)return r.code(404).send({code:"NOT_FOUND"});const result=await repository.getPublicReport(id,s);if(result.state==="ok"){assertSchema(LbtiReportV1Schema,result.report);return result.report}return r.code(result.state==="gone"?410:404).send({code:result.state==="gone"?"GONE":"NOT_FOUND"})});
 for(const route of [{url:"/v1/analyses/:analysisId/share",del:false},{url:"/v1/analyses/:analysisId",del:true}] as const)app.delete(route.url,{schema:{params:Strict({analysisId:Id}),headers:AuthHeaders,response:{204:Type.Null(),404:Error}}},async(q,r)=>{const receipt=bearer((q.headers as any).authorization),ok=receipt&&await(route.del?repository.deleteAnalysis((q.params as any).analysisId,receipt):repository.revokeShare((q.params as any).analysisId,receipt));return ok?r.code(204).send():r.code(404).send({code:"NOT_FOUND"})});
 const cleanup=setInterval(()=>void repository.cleanupExpired().catch(()=>app.log.error({code:"CLEANUP_FAILED"},"retention cleanup failed")),60_000);cleanup.unref();app.addHook("onClose",async()=>clearInterval(cleanup));
 app.setErrorHandler((e,_q,r)=>{if((e as any).validation)return r.code(400).send({code:"INVALID_REQUEST"});app.log.error({code:"INTERNAL_ERROR"},"request failed");return r.code(500).send({code:"INTERNAL_ERROR"})});return app}
