import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import type { Pool } from "pg";

export type AnalysisState = "accepted"|"queued"|"processing"|"validating"|"retry_wait"|"completed"|"failed"|"expired"|"deleted";
export interface ClaimedJob { id:string; analysisId:string; attempt:number; inputPayload:unknown; ownerToken:string; fence:number }
export interface AnalysisRecord { id:string; status:AnalysisState; inputExpiresAt:Date; managementExpiresAt:Date; resultPayload?:unknown; errorCode?:string; retryable?:boolean; publicId?:string; shareExpiresAt?:Date; shareSecret?:string }
export interface CreateAnalysisInput {id:string;installationId:string;idempotencyKey:string;payload:unknown;inputExpiresAt:Date;resultExpiresAt:Date;jobId:string}
export interface CompleteGrant {publicId:string;expiresAt:Date;provider:string;modelId:string;promptVersion:string}
export interface HistoryMatchRow { matchKey:string; occurredAt:Date; payload:unknown }
export interface AnalysisRepository {
  createInstallation(id:string,credential:string):Promise<void>; authenticateInstallation(credential:string):Promise<string|undefined>;
  createAnalysis(input:CreateAnalysisInput):Promise<{analysis:AnalysisRecord;created:boolean;receiptToken:string}>; recoverReceipt(id:string,installationId:string,idempotencyKey:string):Promise<{analysis:AnalysisRecord;receiptToken:string}|undefined>; findByReceipt(id:string,receipt:string):Promise<AnalysisRecord|undefined>;
  claimJob(leaseMs:number,ownerToken:string):Promise<ClaimedJob|undefined>; heartbeat(job:ClaimedJob,leaseMs:number):Promise<boolean>; markValidating(job:ClaimedJob):Promise<boolean>;
  complete(job:ClaimedJob,result:unknown,metrics:unknown,grant:CompleteGrant):Promise<boolean>; failOrRetry(job:ClaimedJob,code:string,retryable:boolean,maxAttempts:number,delayMs:number):Promise<boolean>;
  retryAnalysis(id:string,receipt:string,maxAttempts:number):Promise<boolean>; createShareSession(publicId:string,secret:string,sessionToken:string,expiresAt:Date):Promise<"created"|"not_found"|"gone">;
  getPublicReport(publicId:string,sessionToken:string):Promise<{state:"ok";report:unknown}|{state:"not_found"|"gone"}>; revokeShare(id:string,receipt:string):Promise<boolean>; deleteAnalysis(id:string,receipt:string):Promise<boolean>;
  cleanupExpired():Promise<number>; reserveBudget(limit:number):Promise<boolean>;
  saveMatches(installationId:string,matches:HistoryMatchRow[]):Promise<number>;
  createHistoryViewer(installationId:string):Promise<string>; revokeHistoryViewer(installationId:string):Promise<void>;
  createHistorySession(viewerToken:string,sessionToken:string,expiresAt:Date):Promise<"created"|"not_found"|"gone">;
  getMatchesBySession(sessionToken:string):Promise<{installationId:string;matches:unknown[]}|undefined>;
  deleteMatchesBySession(sessionToken:string):Promise<boolean>;
}
export const hashSecret=(secret:string,pepper:string)=>createHash("sha256").update(secret).update(pepper).digest("hex");
export function secretMatches(secret:string,expectedHex:string,pepper:string){const actual=Buffer.from(hashSecret(secret,pepper),"hex"),expected=Buffer.from(expectedHex,"hex");return actual.length===expected.length&&timingSafeEqual(actual,expected)}
const derive=(pepper:string,purpose:string,id:string)=>createHmac("sha256",pepper).update(`${purpose}\0${id}`).digest("base64url");
export function encryptJson(value:unknown,key:Buffer){if(key.length!==32)throw new Error("encryption key must contain 32 bytes");const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key,iv),body=Buffer.concat([cipher.update(JSON.stringify(value),"utf8"),cipher.final()]);return[iv,cipher.getAuthTag(),body].map(x=>x.toString("base64url")).join(".")}
export function decryptJson(value:string,key:Buffer):unknown{const parts=value.split(".");if(parts.length!==3)throw new Error("invalid encrypted payload");const [iv,tag,body]=parts.map(x=>Buffer.from(x!,"base64url")),decipher=createDecipheriv("aes-256-gcm",key,iv!);decipher.setAuthTag(tag!);return JSON.parse(Buffer.concat([decipher.update(body!),decipher.final()]).toString("utf8"))}

export class Repository implements AnalysisRepository {
 constructor(private readonly pool:Pool,private readonly pepper:string,private readonly encryptionKey:Buffer){}
 async createInstallation(id:string,credential:string){await this.pool.query("INSERT INTO installations(id,credential_hash) VALUES($1,$2)",[id,hashSecret(credential,this.pepper)])}
 async authenticateInstallation(credential:string){const candidate=hashSecret(credential,this.pepper),{rows}=await this.pool.query<{id:string;credential_hash:string}>("SELECT id,credential_hash FROM installations WHERE credential_hash=$1 AND revoked_at IS NULL",[candidate]);const row=rows[0];if(!row||!secretMatches(credential,row.credential_hash,this.pepper))return undefined;await this.pool.query("UPDATE installations SET last_seen_at=now() WHERE id=$1",[row.id]);return row.id}
 async createAnalysis(input:CreateAnalysisInput){const receiptToken=derive(this.pepper,"receipt",`${input.installationId}:${input.idempotencyKey}`),client=await this.pool.connect();try{await client.query("BEGIN");const inserted=await client.query<any>(`INSERT INTO analyses(id,installation_id,idempotency_key_hash,status,schema_version,receipt_hash,input_payload_encrypted,input_expires_at,result_expires_at) VALUES($1,$2,$3,'queued',1,$4,$5,$6,$7) ON CONFLICT(installation_id,idempotency_key_hash) DO NOTHING RETURNING *`,[input.id,input.installationId,hashSecret(input.idempotencyKey,this.pepper),hashSecret(receiptToken,this.pepper),encryptJson(input.payload,this.encryptionKey),input.inputExpiresAt,input.resultExpiresAt]);let row=inserted.rows[0],created=Boolean(row);if(!row)row=(await client.query("SELECT * FROM analyses WHERE installation_id=$1 AND idempotency_key_hash=$2",[input.installationId,hashSecret(input.idempotencyKey,this.pepper)])).rows[0];else await client.query("INSERT INTO analysis_jobs(id,analysis_id,attempt,status) VALUES($1,$2,1,'queued')",[input.jobId,input.id]);await client.query("COMMIT");return{analysis:mapAnalysis(row),created,receiptToken}}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
 async recoverReceipt(id:string,installationId:string,idempotencyKey:string){const keyHash=hashSecret(idempotencyKey,this.pepper),{rows}=await this.pool.query<any>("SELECT * FROM analyses WHERE id=$1 AND installation_id=$2 AND idempotency_key_hash=$3 AND status NOT IN ('deleted','expired') AND result_expires_at>now()",[id,installationId,keyHash]);const row=rows[0];if(!row||!secretMatches(idempotencyKey,row.idempotency_key_hash,this.pepper))return undefined;const receiptToken=derive(this.pepper,"receipt",`${installationId}:${idempotencyKey}`);if(!secretMatches(receiptToken,row.receipt_hash,this.pepper))return undefined;return{analysis:mapAnalysis(row),receiptToken}}
 async findByReceipt(id:string,receipt:string){const {rows}=await this.pool.query<any>(`SELECT a.*,g.public_id,g.expires_at share_expires_at,g.secret_hash FROM analyses a LEFT JOIN share_grants g ON g.analysis_id=a.id AND g.revoked_at IS NULL WHERE a.id=$1 AND a.receipt_hash=$2`,[id,hashSecret(receipt,this.pepper)]);const row=rows[0];if(!row||!secretMatches(receipt,row.receipt_hash,this.pepper))return undefined;const record=mapAnalysis(row);if(row.public_id&&row.secret_hash){const secret=derive(this.pepper,"share",row.public_id);if(secretMatches(secret,row.secret_hash,this.pepper))record.shareSecret=secret}return record}
 async claimJob(leaseMs:number,ownerToken:string){const client=await this.pool.connect();try{await client.query("BEGIN");const {rows}=await client.query<any>(`WITH candidate AS (SELECT id FROM analysis_jobs WHERE ((status='queued' AND available_at<=now()) OR (status='processing' AND lease_until<now())) ORDER BY queued_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE analysis_jobs j SET status='processing',owner_token=$2,fence=fence+1,started_at=COALESCE(started_at,now()),lease_until=now()+($1*interval '1 millisecond') FROM candidate WHERE j.id=candidate.id RETURNING j.*`,[leaseMs,ownerToken]);const job=rows[0];if(!job){await client.query("COMMIT");return undefined}const analysis=(await client.query<any>("UPDATE analyses SET status='processing' WHERE id=$1 AND status IN ('queued','processing','validating','retry_wait') RETURNING input_payload_encrypted",[job.analysis_id])).rows[0];if(!analysis?.input_payload_encrypted)throw new Error("claimable job has no input");await client.query("COMMIT");return{id:job.id,analysisId:job.analysis_id,attempt:job.attempt,inputPayload:decryptJson(analysis.input_payload_encrypted,this.encryptionKey),ownerToken,fence:job.fence}}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
 async heartbeat(job:ClaimedJob,leaseMs:number){const r=await this.pool.query("UPDATE analysis_jobs SET lease_until=now()+($4*interval '1 millisecond') WHERE id=$1 AND status='processing' AND owner_token=$2 AND fence=$3",[job.id,job.ownerToken,job.fence,leaseMs]);return r.rowCount===1}
 async markValidating(job:ClaimedJob){const r=await this.pool.query(`WITH owned AS (SELECT analysis_id FROM analysis_jobs WHERE id=$1 AND status='processing' AND owner_token=$2 AND fence=$3 AND lease_until>now()) UPDATE analyses SET status='validating' WHERE id IN (SELECT analysis_id FROM owned) AND status='processing'`,[job.id,job.ownerToken,job.fence]);return r.rowCount===1}
 async complete(job:ClaimedJob,result:unknown,metrics:unknown,grant:CompleteGrant){const client=await this.pool.connect();try{await client.query("BEGIN");const owned=await client.query("UPDATE analysis_jobs SET status='completed',lease_until=NULL,finished_at=now(),provider=$4,model_id=$5,prompt_version=$6 WHERE id=$1 AND status='processing' AND owner_token=$2 AND fence=$3 AND lease_until>now()",[job.id,job.ownerToken,job.fence,grant.provider,grant.modelId,grant.promptVersion]);if(owned.rowCount!==1){await client.query("ROLLBACK");return false}const changed=await client.query("UPDATE analyses SET status='completed',result_version=1,result_payload=$2,aggregate_metrics=$3,input_payload_encrypted=NULL WHERE id=$1 AND status='validating'",[job.analysisId,result,metrics]);if(changed.rowCount!==1)throw new Error("invalid completion state");const secret=derive(this.pepper,"share",grant.publicId);await client.query("INSERT INTO share_grants(public_id,analysis_id,secret_hash,expires_at) VALUES($1,$2,$3,$4) ON CONFLICT(analysis_id) DO NOTHING",[grant.publicId,job.analysisId,hashSecret(secret,this.pepper),grant.expiresAt]);await client.query("COMMIT");return true}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
 async failOrRetry(job:ClaimedJob,code:string,retryable:boolean,maxAttempts:number,delayMs:number){const client=await this.pool.connect();try{await client.query("BEGIN");const owned=await client.query("UPDATE analysis_jobs SET status=$4,error_code=$5,lease_until=NULL,finished_at=now() WHERE id=$1 AND status='processing' AND owner_token=$2 AND fence=$3 AND lease_until>now()",[job.id,job.ownerToken,job.fence,"failed",code]);if(owned.rowCount!==1){await client.query("ROLLBACK");return false}if(retryable&&job.attempt<maxAttempts){await client.query("UPDATE analyses SET status='retry_wait',retry_count=retry_count+1,error_code=$2,retryable=true WHERE id=$1 AND status IN ('processing','validating')",[job.analysisId,code]);await client.query("INSERT INTO analysis_jobs(id,analysis_id,attempt,status,available_at) VALUES($1,$2,$3,'queued',now()+($4*interval '1 millisecond'))",[`${job.analysisId}_${job.attempt+1}`,job.analysisId,job.attempt+1,delayMs])}else await client.query("UPDATE analyses SET status='failed',error_code=$2,retryable=$3 WHERE id=$1 AND status IN ('processing','validating')",[job.analysisId,code,retryable]);await client.query("COMMIT");return true}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
 async retryAnalysis(id:string,receipt:string,maxAttempts:number){const client=await this.pool.connect();try{await client.query("BEGIN");const row=(await client.query<{receipt_hash:string;status:AnalysisState;retryable:boolean|null}>("SELECT receipt_hash,status,retryable FROM analyses WHERE id=$1 AND receipt_hash=$2 FOR UPDATE",[id,hashSecret(receipt,this.pepper)])).rows[0];if(!row||!secretMatches(receipt,row.receipt_hash,this.pepper)||row.status!=="failed"||!row.retryable){await client.query("ROLLBACK");return false}const attempt=Number((await client.query<{attempt:string}>("SELECT COALESCE(max(attempt),0)+1 attempt FROM analysis_jobs WHERE analysis_id=$1",[id])).rows[0]!.attempt);if(attempt>maxAttempts){await client.query("ROLLBACK");return false}await client.query("INSERT INTO analysis_jobs(id,analysis_id,attempt,status) VALUES($1,$2,$3,'queued')",[`${id}_${attempt}`,id,attempt]);const changed=await client.query("UPDATE analyses SET status='queued',error_code=NULL,retryable=NULL WHERE id=$1 AND status='failed' AND retryable=true",[id]);if(changed.rowCount!==1)throw new Error("invalid manual retry state");await client.query("COMMIT");return true}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
 async createShareSession(publicId:string,secret:string,sessionToken:string,expiresAt:Date){const client=await this.pool.connect();try{await client.query("BEGIN");const {rows}=await client.query<any>("SELECT * FROM share_grants WHERE public_id=$1 FOR UPDATE",[publicId]);const g=rows[0];if(!g){await client.query("ROLLBACK");return"not_found" as const}if(g.revoked_at||new Date(g.expires_at)<=new Date()){await client.query("ROLLBACK");return"gone" as const}if(!secretMatches(secret,g.secret_hash,this.pepper)){await client.query("ROLLBACK");return"not_found" as const}if(g.view_count>=g.max_views){await client.query("ROLLBACK");return"gone" as const}await client.query("UPDATE share_grants SET view_count=view_count+1 WHERE public_id=$1",[publicId]);await client.query("INSERT INTO share_sessions(session_hash,public_id,expires_at) VALUES($1,$2,$3)",[hashSecret(sessionToken,this.pepper),publicId,expiresAt]);await client.query("COMMIT");return"created" as const}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
 async getPublicReport(publicId:string,sessionToken:string){const {rows}=await this.pool.query<any>(`SELECT s.session_hash,s.expires_at session_expires,s.revoked_at session_revoked,g.expires_at grant_expires,g.revoked_at grant_revoked,a.status,a.result_payload FROM share_sessions s JOIN share_grants g ON g.public_id=s.public_id JOIN analyses a ON a.id=g.analysis_id WHERE s.public_id=$1 AND s.session_hash=$2`,[publicId,hashSecret(sessionToken,this.pepper)]);const r=rows[0];if(!r||!secretMatches(sessionToken,r.session_hash,this.pepper))return{state:"not_found" as const};if(r.session_revoked||r.grant_revoked||new Date(r.session_expires)<=new Date()||new Date(r.grant_expires)<=new Date()||r.status!=="completed")return{state:"gone" as const};return{state:"ok" as const,report:r.result_payload}}
 async revokeShare(id:string,receipt:string){const a=await this.findByReceipt(id,receipt);if(!a)return false;await this.pool.query("UPDATE share_grants SET revoked_at=now() WHERE analysis_id=$1",[id]);await this.pool.query("UPDATE share_sessions SET revoked_at=now() WHERE public_id IN (SELECT public_id FROM share_grants WHERE analysis_id=$1)",[id]);return true}
 async deleteAnalysis(id:string,receipt:string){const a=await this.findByReceipt(id,receipt);if(!a)return false;await this.pool.query("UPDATE analyses SET status='deleted',input_payload_encrypted=NULL,result_payload=NULL,aggregate_metrics=NULL,deleted_at=now() WHERE id=$1",[id]);await this.revokeShare(id,receipt);return true}
 async cleanupExpired(){const r=await this.pool.query(`WITH expired AS (UPDATE analyses SET status='expired',input_payload_encrypted=NULL,result_payload=NULL,aggregate_metrics=NULL,deleted_at=now() WHERE status NOT IN ('deleted','expired') AND result_expires_at<=now() RETURNING id) UPDATE share_grants SET revoked_at=now() WHERE analysis_id IN (SELECT id FROM expired)`);await this.pool.query("DELETE FROM share_sessions WHERE expires_at<=now() OR revoked_at IS NOT NULL");await this.pool.query("UPDATE analyses SET input_payload_encrypted=NULL WHERE input_expires_at<=now()");return r.rowCount??0}
 async reserveBudget(limit:number){const r=await this.pool.query(`INSERT INTO provider_daily_budget(day,spent) VALUES(current_date,1) ON CONFLICT(day) DO UPDATE SET spent=provider_daily_budget.spent+1 WHERE provider_daily_budget.spent<$1 RETURNING spent`,[limit]);return r.rowCount===1}
 async saveMatches(installationId:string,matches:HistoryMatchRow[]){if(!matches.length)return 0;const values=matches.map((m,i)=>({installationId,matchKey:m.matchKey,occurredAt:m.occurredAt,payload:encryptJson(m.payload,this.encryptionKey),offset:i*4})),placeholders=values.map(v=>"("+["$"+(v.offset+1),"$"+(v.offset+2),"$"+(v.offset+3),"$"+(v.offset+4)].join(",")+")").join(","),params:unknown[]=[];for(const v of values)params.push(v.installationId,v.matchKey,v.occurredAt,v.payload);const r=await this.pool.query(`INSERT INTO match_history(installation_id,match_key,occurred_at,payload_encrypted) VALUES ${placeholders} ON CONFLICT(installation_id,match_key) DO NOTHING`,params);return r.rowCount??0}
 async createHistoryViewer(installationId:string){const secret=derive(this.pepper,"history-viewer",installationId),hash=hashSecret(secret,this.pepper),expiresAt=new Date(Date.now()+90*86400_000);await this.pool.query(`INSERT INTO history_viewers(installation_id,secret_hash,expires_at) VALUES($1,$2,$3) ON CONFLICT(installation_id) DO UPDATE SET secret_hash=EXCLUDED.secret_hash,expires_at=EXCLUDED.expires_at,revoked_at=NULL`,[installationId,hash,expiresAt]);return secret}
 async revokeHistoryViewer(installationId:string){await this.pool.query("UPDATE history_viewers SET revoked_at=now() WHERE installation_id=$1 AND revoked_at IS NULL",[installationId]);await this.pool.query("UPDATE history_sessions SET revoked_at=now() WHERE installation_id=$1 AND revoked_at IS NULL",[installationId])}
 async createHistorySession(viewerToken:string,sessionToken:string,expiresAt:Date){const client=await this.pool.connect();try{await client.query("BEGIN");const {rows}=await client.query<any>("SELECT * FROM history_viewers WHERE secret_hash=$1 FOR UPDATE",[hashSecret(viewerToken,this.pepper)]);const g=rows[0];if(!g||!secretMatches(viewerToken,g.secret_hash,this.pepper)){await client.query("ROLLBACK");return"not_found" as const}if(g.revoked_at||new Date(g.expires_at)<=new Date()){await client.query("ROLLBACK");return"gone" as const}await client.query("INSERT INTO history_sessions(session_hash,installation_id,expires_at) VALUES($1,$2,$3) ON CONFLICT(session_hash) DO UPDATE SET expires_at=EXCLUDED.expires_at,revoked_at=NULL",[hashSecret(sessionToken,this.pepper),g.installation_id,expiresAt]);await client.query("COMMIT");return"created" as const}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
 async getMatchesBySession(sessionToken:string){const {rows}=await this.pool.query<any>(`SELECT s.installation_id,s.expires_at,s.revoked_at,m.payload_encrypted FROM history_sessions s LEFT JOIN match_history m ON m.installation_id=s.installation_id WHERE s.session_hash=$1`,[hashSecret(sessionToken,this.pepper)]);const row=rows[0];if(!row||!secretMatches(sessionToken,row.session_hash,this.pepper))return undefined;if(row.revoked_at||new Date(row.expires_at)<=new Date())return undefined;const matches=rows.map((r:any)=>decryptJson(r.payload_encrypted,this.encryptionKey));return{installationId:row.installation_id,matches}}
 async deleteMatchesBySession(sessionToken:string){const {rows}=await this.pool.query<any>("SELECT installation_id,expires_at,revoked_at FROM history_sessions WHERE session_hash=$1",[hashSecret(sessionToken,this.pepper)]);const row=rows[0];if(!row||!secretMatches(sessionToken,row.session_hash,this.pepper)||row.revoked_at||new Date(row.expires_at)<=new Date())return false;await this.pool.query("DELETE FROM match_history WHERE installation_id=$1",[row.installation_id]);return true}
}
function mapAnalysis(row:any):AnalysisRecord{return{id:row.id,status:row.status,inputExpiresAt:new Date(row.input_expires_at),managementExpiresAt:new Date(row.result_expires_at),resultPayload:row.result_payload,errorCode:row.error_code,retryable:row.retryable,publicId:row.public_id,shareExpiresAt:row.share_expires_at?new Date(row.share_expires_at):undefined}}
