import { createHmac, randomUUID } from "node:crypto";
import type { AnalysisRecord,AnalysisRepository,ClaimedJob,CompleteGrant,CreateAnalysisInput } from "./index.js";
const derive=(pepper:string,purpose:string,id:string)=>createHmac("sha256",pepper).update(`${purpose}\0${id}`).digest("base64url");
type Stored=AnalysisRecord&{installationId:string;key:string;receipt:string;payload:unknown;resultExpiresAt:Date};
type Job={id:string;analysisId:string;attempt:number;status:"queued"|"processing"|"completed"|"failed";availableAt:number;leaseUntil:number;owner?:string;fence:number};
export class MemoryRepository implements AnalysisRepository{
 private installations=new Map<string,string>();private analyses=new Map<string,Stored>();private jobs:Job[]=[];private grants=new Map<string,{analysisId:string;secret:string;expiresAt:Date;revoked:boolean;views:number}>();private sessions=new Map<string,{publicId:string;expiresAt:Date;revoked:boolean}>();private budgetDay="";private spent=0;
 constructor(private readonly pepper="test-pepper"){}
 async createInstallation(id:string,credential:string){this.installations.set(credential,id)} async authenticateInstallation(c:string){return this.installations.get(c)}
 async createAnalysis(i:CreateAnalysisInput){const existing=[...this.analyses.values()].find(a=>a.installationId===i.installationId&&a.key===i.idempotencyKey);const receipt=derive(this.pepper,"receipt",`${i.installationId}:${i.idempotencyKey}`);if(existing)return{analysis:this.view(existing),created:false,receiptToken:receipt};const a:Stored={id:i.id,status:"queued",inputExpiresAt:i.inputExpiresAt,resultExpiresAt:i.resultExpiresAt,installationId:i.installationId,key:i.idempotencyKey,receipt,payload:i.payload};this.analyses.set(i.id,a);this.jobs.push({id:i.jobId,analysisId:i.id,attempt:1,status:"queued",availableAt:Date.now(),leaseUntil:0,fence:0});return{analysis:this.view(a),created:true,receiptToken:receipt}}
 async findByReceipt(id:string,r:string){const a=this.analyses.get(id);return a&&a.receipt===r?this.view(a):undefined}
 async claimJob(ms:number,owner:string){const now=Date.now(),j=this.jobs.find(x=>(x.status==="queued"&&x.availableAt<=now)||(x.status==="processing"&&x.leaseUntil<now));if(!j)return undefined;j.status="processing";j.owner=owner;j.fence++;j.leaseUntil=now+ms;const a=this.analyses.get(j.analysisId)!;a.status="processing";return{id:j.id,analysisId:j.analysisId,attempt:j.attempt,inputPayload:a.payload,ownerToken:owner,fence:j.fence}}
 private owned(x:ClaimedJob){return this.jobs.find(j=>j.id===x.id&&j.status==="processing"&&j.owner===x.ownerToken&&j.fence===x.fence&&j.leaseUntil>Date.now())}
 async heartbeat(j:ClaimedJob,ms:number){const x=this.owned(j);if(!x)return false;x.leaseUntil=Date.now()+ms;return true}async markValidating(j:ClaimedJob){if(!this.owned(j))return false;this.analyses.get(j.analysisId)!.status="validating";return true}
 async complete(j:ClaimedJob,result:unknown,_metrics:unknown,g:CompleteGrant){const x=this.owned(j),a=this.analyses.get(j.analysisId);if(!x||!a||a.status!=="validating")return false;x.status="completed";a.status="completed";a.resultPayload=result;a.payload=undefined;const secret=derive(this.pepper,"share",g.publicId);this.grants.set(g.publicId,{analysisId:j.analysisId,secret,expiresAt:g.expiresAt,revoked:false,views:0});a.publicId=g.publicId;a.shareExpiresAt=g.expiresAt;a.shareSecret=secret;return true}
 async failOrRetry(j:ClaimedJob,code:string,retryable:boolean,max:number,delay:number){const x=this.owned(j),a=this.analyses.get(j.analysisId);if(!x||!a)return false;x.status="failed";a.errorCode=code;a.retryable=retryable;if(retryable&&j.attempt<max){a.status="retry_wait";this.jobs.push({id:`${j.analysisId}_${j.attempt+1}`,analysisId:j.analysisId,attempt:j.attempt+1,status:"queued",availableAt:Date.now()+delay,leaseUntil:0,fence:0})}else a.status="failed";return true}
 async retryAnalysis(id:string,r:string,max:number){const a=this.analyses.get(id);if(!a||a.receipt!==r||a.status!=="failed"||!a.retryable)return false;const attempt=Math.max(...this.jobs.filter(j=>j.analysisId===id).map(j=>j.attempt))+1;if(attempt>max)return false;a.status="queued";a.errorCode=undefined;a.retryable=undefined;this.jobs.push({id:`${id}_${attempt}`,analysisId:id,attempt,status:"queued",availableAt:Date.now(),leaseUntil:0,fence:0});return true}
 async createShareSession(id:string,secret:string,token:string,expires:Date){const g=this.grants.get(id);if(!g||g.secret!==secret)return"not_found";if(g.revoked||g.expiresAt<=new Date()||g.views>=100)return"gone";g.views++;this.sessions.set(token,{publicId:id,expiresAt:expires,revoked:false});return"created"}
 async getPublicReport(id:string,token:string){const s=this.sessions.get(token),g=this.grants.get(id);if(!s||s.publicId!==id)return{state:"not_found" as const};if(s.revoked||s.expiresAt<=new Date()||!g||g.revoked||g.expiresAt<=new Date())return{state:"gone" as const};return{state:"ok" as const,report:this.analyses.get(g.analysisId)!.resultPayload}}
 async revokeShare(id:string,r:string){const a=this.analyses.get(id);if(!a||a.receipt!==r)return false;for(const [publicId,g]of this.grants)if(g.analysisId===id){g.revoked=true;for(const s of this.sessions.values())if(s.publicId===publicId)s.revoked=true}return true}
 async deleteAnalysis(id:string,r:string){const a=this.analyses.get(id);if(!a||a.receipt!==r)return false;await this.revokeShare(id,r);a.status="deleted";a.payload=undefined;a.resultPayload=undefined;return true}
 async cleanupExpired(){let n=0;for(const a of this.analyses.values()){if(a.inputExpiresAt<=new Date())a.payload=undefined;if(a.resultExpiresAt<=new Date()&&a.status!=="deleted"&&a.status!=="expired"){a.status="expired";a.resultPayload=undefined;n++}}return n}
 async reserveBudget(limit:number){const day=new Date().toISOString().slice(0,10);if(day!==this.budgetDay){this.budgetDay=day;this.spent=0}if(this.spent>=limit)return false;this.spent++;return true}
 private view(a:Stored){const v:AnalysisRecord={id:a.id,status:a.status,inputExpiresAt:a.inputExpiresAt,resultPayload:a.resultPayload,errorCode:a.errorCode,retryable:a.retryable,publicId:a.publicId,shareExpiresAt:a.shareExpiresAt,shareSecret:a.shareSecret};return v}
 countJobs(){return this.jobs.length} expireLease(id:string){const j=this.jobs.find(x=>x.id===id);if(j)j.leaseUntil=0} static owner(){return randomUUID()}
}
